# Generated by Django 5.2 on 2025-04-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('street_number', models.CharField(blank=True, max_length=10, null=True)),
                ('street_name', models.CharField(blank=True, max_length=100, null=True)),
                ('apt_number', models.CharField(blank=True, max_length=10, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_registration', models.DateField(blank=True, null=True)),
                ('party', models.CharField(blank=True, max_length=50, null=True)),
                ('precinct', models.CharField(blank=True, max_length=10, null=True)),
                ('v20state', models.BooleanField(default=False)),
                ('v21town', models.BooleanField(default=False)),
                ('v21primary', models.BooleanField(default=False)),
                ('v22general', models.BooleanField(default=False)),
                ('v23town', models.BooleanField(default=False)),
                ('voter_score', models.IntegerField(default=0)),
            ],
        ),
    ]
